Está desarrollado, especialmente al principio en vsCode. A partir de ej 9 aquí igual.

In [1]:
import numpy as np

# Random

In [2]:
a = np.random.random((2, 3, 5))
a

array([[[0.32867628, 0.35073552, 0.13998989, 0.11632413, 0.85076657],
        [0.34830061, 0.24800611, 0.65361982, 0.84371955, 0.32066555],
        [0.82654795, 0.82119937, 0.88203233, 0.44121857, 0.07420423]],

       [[0.44808333, 0.51665496, 0.38625333, 0.25536305, 0.59485847],
        [0.38121872, 0.41420294, 0.91397568, 0.13894659, 0.16683535],
        [0.4240922 , 0.13420218, 0.60523859, 0.32837709, 0.88692215]]])

RAND creates the array from given numbers inside the function, so just **one parenthesis** (for the function) is enough:

In [3]:
a2 = np.random.rand(2, 3, 5)
a2

array([[[0.02588773, 0.09683822, 0.88019871, 0.52145382, 0.79915295],
        [0.49141877, 0.07682388, 0.14202446, 0.34084556, 0.83771725],
        [0.39241765, 0.55425858, 0.91941032, 0.1015146 , 0.86423642]],

       [[0.96454578, 0.34170861, 0.21344541, 0.37625821, 0.92438214],
        [0.30118175, 0.4769497 , 0.46409197, 0.52634162, 0.41407594],
        [0.62991682, 0.35478619, 0.68988959, 0.91617484, 0.23127138]]])

In [4]:
a3 = np.random.random_sample((2, 3, 5))
a3

array([[[0.84171315, 0.64896034, 0.05473123, 0.27420126, 0.31965437],
        [0.53220958, 0.04892052, 0.85845317, 0.80986537, 0.5776321 ],
        [0.29390114, 0.77752001, 0.52091615, 0.26583289, 0.73615348]],

       [[0.12495233, 0.05411803, 0.09852396, 0.28054521, 0.0592931 ],
        [0.20295282, 0.43406029, 0.88657283, 0.11218157, 0.19281145],
        [0.09918209, 0.78360197, 0.03066254, 0.11786018, 0.09820049]]])

In [5]:
a4 = np.random.ranf((2, 3, 5))
a4

array([[[0.27751327, 0.41692272, 0.92503347, 0.39685426, 0.64513305],
        [0.21169812, 0.90100838, 0.18172431, 0.3191464 , 0.95470742],
        [0.1369501 , 0.97512897, 0.67228428, 0.56235521, 0.8630947 ]],

       [[0.13879597, 0.83218542, 0.37756588, 0.91862809, 0.01612515],
        [0.41248803, 0.80293398, 0.39166802, 0.7192624 , 0.44663361],
        [0.7741541 , 0.89247164, 0.72114331, 0.56340212, 0.97029654]]])

In [6]:
a5 = np.random.sample((2, 3, 5))
a5

array([[[0.33295385, 0.18253003, 0.14873063, 0.60659225, 0.27554334],
        [0.55631748, 0.45388872, 0.55160038, 0.77236359, 0.26063936],
        [0.53683899, 0.91028135, 0.34948042, 0.09135387, 0.66184918]],

       [[0.69588076, 0.08858657, 0.19594821, 0.44563204, 0.62373394],
        [0.04973394, 0.03125128, 0.53270169, 0.69479091, 0.78905624],
        [0.93665437, 0.67078953, 0.05848314, 0.08325518, 0.47875779]]])

# Arrays 

In [7]:
#5&6. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5, 2, 3)) 
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [8]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). 
# Assign the transposed array to variable "c".

## a is of shape (2, 3, 5), b shape is (5, 2, 3)
## We need to make axe 1 to 0, 2 to 1 and 0 to 3:
c = np.transpose(b, (1, 2, 0))
print('a= \n', a, '\n')
print('b= \n', b, '\n')
print('c= \n', c, '\n')

a= 
 [[[0.32867628 0.35073552 0.13998989 0.11632413 0.85076657]
  [0.34830061 0.24800611 0.65361982 0.84371955 0.32066555]
  [0.82654795 0.82119937 0.88203233 0.44121857 0.07420423]]

 [[0.44808333 0.51665496 0.38625333 0.25536305 0.59485847]
  [0.38121872 0.41420294 0.91397568 0.13894659 0.16683535]
  [0.4240922  0.13420218 0.60523859 0.32837709 0.88692215]]] 

b= 
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]] 

c= 
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]] 



In [9]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". 

##--> If we were asked for a total sum of the elements 
## (but I assume we are not, just that I saw somewhere that we had to use the sum fn: 
## d = np.sum((a, c))
## print('d= \n', d, '\n')

# But what we want is another array, so no sum fn here: 
d = a + c
print('d= \n', d, '\n')
##---> Works. 

d= 
 [[[1.32867628 1.35073552 1.13998989 1.11632413 1.85076657]
  [1.34830061 1.24800611 1.65361982 1.84371955 1.32066555]
  [1.82654795 1.82119937 1.88203233 1.44121857 1.07420423]]

 [[1.44808333 1.51665496 1.38625333 1.25536305 1.59485847]
  [1.38121872 1.41420294 1.91397568 1.13894659 1.16683535]
  [1.4240922  1.13420218 1.60523859 1.32837709 1.88692215]]] 



11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [10]:
print('a= \n', a, '\n')
print('d= \n', d, '\n')

a= 
 [[[0.32867628 0.35073552 0.13998989 0.11632413 0.85076657]
  [0.34830061 0.24800611 0.65361982 0.84371955 0.32066555]
  [0.82654795 0.82119937 0.88203233 0.44121857 0.07420423]]

 [[0.44808333 0.51665496 0.38625333 0.25536305 0.59485847]
  [0.38121872 0.41420294 0.91397568 0.13894659 0.16683535]
  [0.4240922  0.13420218 0.60523859 0.32837709 0.88692215]]] 

d= 
 [[[1.32867628 1.35073552 1.13998989 1.11632413 1.85076657]
  [1.34830061 1.24800611 1.65361982 1.84371955 1.32066555]
  [1.82654795 1.82119937 1.88203233 1.44121857 1.07420423]]

 [[1.44808333 1.51665496 1.38625333 1.25536305 1.59485847]
  [1.38121872 1.41420294 1.91397568 1.13894659 1.16683535]
  [1.4240922  1.13420218 1.60523859 1.32837709 1.88692215]]] 



we are just adding 1 to each element, as d has been created with the `one` fn. 

12. Multiply a and c. Assign the result to e.

In [11]:
e = a * c
e

array([[[0.32867628, 0.35073552, 0.13998989, 0.11632413, 0.85076657],
        [0.34830061, 0.24800611, 0.65361982, 0.84371955, 0.32066555],
        [0.82654795, 0.82119937, 0.88203233, 0.44121857, 0.07420423]],

       [[0.44808333, 0.51665496, 0.38625333, 0.25536305, 0.59485847],
        [0.38121872, 0.41420294, 0.91397568, 0.13894659, 0.16683535],
        [0.4240922 , 0.13420218, 0.60523859, 0.32837709, 0.88692215]]])

13. Does e equal to a? Why or why not?

In [12]:
print('a= \n', a, '\n')
print('c= \n', c, '\n')
print('e= \n', e, '\n')
e == a

a= 
 [[[0.32867628 0.35073552 0.13998989 0.11632413 0.85076657]
  [0.34830061 0.24800611 0.65361982 0.84371955 0.32066555]
  [0.82654795 0.82119937 0.88203233 0.44121857 0.07420423]]

 [[0.44808333 0.51665496 0.38625333 0.25536305 0.59485847]
  [0.38121872 0.41420294 0.91397568 0.13894659 0.16683535]
  [0.4240922  0.13420218 0.60523859 0.32837709 0.88692215]]] 

c= 
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]] 

e= 
 [[[0.32867628 0.35073552 0.13998989 0.11632413 0.85076657]
  [0.34830061 0.24800611 0.65361982 0.84371955 0.32066555]
  [0.82654795 0.82119937 0.88203233 0.44121857 0.07420423]]

 [[0.44808333 0.51665496 0.38625333 0.25536305 0.59485847]
  [0.38121872 0.41420294 0.91397568 0.13894659 0.16683535]
  [0.4240922  0.13420218 0.60523859 0.32837709 0.88692215]]] 



array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

`a = e` because we are just multiplying `a` by one.

**14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"**

In [13]:
d_max, d_min, d_mean = np.amax(d), np.amin(d), np.mean(d)
print(d_max, d_min, d_mean)

1.9139756823555483 1.0742042331578827 1.461374370035919


**15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.**

In [14]:
f = np.empty((2, 3, 5))
##---> Use it with caution, as it doesn't initialze the values (unlike np.ceros)
f
##--->Se how here in Jupyter, it is taking the values of the previous array! In vsCode, print(f) doesn't print anything

array([[[0.32867628, 0.35073552, 0.13998989, 0.11632413, 0.85076657],
        [0.34830061, 0.24800611, 0.65361982, 0.84371955, 0.32066555],
        [0.82654795, 0.82119937, 0.88203233, 0.44121857, 0.07420423]],

       [[0.44808333, 0.51665496, 0.38625333, 0.25536305, 0.59485847],
        [0.38121872, 0.41420294, 0.91397568, 0.13894659, 0.16683535],
        [0.4240922 , 0.13420218, 0.60523859, 0.32837709, 0.88692215]]])

**16. Populate the values in f. For each value in d:**

* if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
* If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
* If a value equals to d_mean, assign 50 to the corresponding value in f.
* Assign 0 to the corresponding value(s) in f for d_min in d.
* Assign 100 to the corresponding value(s) in f for d_max in d.

In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [15]:
f = np.random.rand(2, 3, 5)
print(f)

[[[0.43239355 0.61527144 0.81828862 0.18180565 0.72953439]
  [0.15083346 0.55346094 0.75194568 0.52944421 0.5005854 ]
  [0.15602136 0.96255137 0.14529897 0.74579909 0.37177604]]

 [[0.38176634 0.76587859 0.83128187 0.44446682 0.75743077]
  [0.96256696 0.09453707 0.00331646 0.0947169  0.89439987]
  [0.3266463  0.71327135 0.49454884 0.12641841 0.14476288]]]


#### Tests:

**`for x in f`** recorre sólo los grupos exteriores. Comprobado imprimendo algo distinto en cada iteración

In [16]:
for x in f:
    print(x)
    print("comprobación")

[[0.43239355 0.61527144 0.81828862 0.18180565 0.72953439]
 [0.15083346 0.55346094 0.75194568 0.52944421 0.5005854 ]
 [0.15602136 0.96255137 0.14529897 0.74579909 0.37177604]]
comprobación
[[0.38176634 0.76587859 0.83128187 0.44446682 0.75743077]
 [0.96256696 0.09453707 0.00331646 0.0947169  0.89439987]
 [0.3266463  0.71327135 0.49454884 0.12641841 0.14476288]]
comprobación


In [17]:
# i,j,k,l=0, 0, 0, 0
# ERROR porque no se pueden comparar muchos valores con 1
for x in f:
        if x > d_min and x < d_mean:

SyntaxError: unexpected EOF while parsing (<ipython-input-17-74a7fa8be09c>, line 4)

.DO: Es normal que lo de arriba no asigne, pero no tengo super claro porqué. 

MORE TESTS JUST FOR ME:

In [ ]:
for x in np.nditer(f):
        if x > d_min and x < d_mean:
                f[np.nditer(f)] = 25
                print(f[np.nditer(f)])
        elif x > d_mean and x < d_max:
                f[np.nditer(f)] = 75
        elif x == d_mean:
                f[np.nditer(f)] = 75
        elif x == d_min:
                f[np.nditer(f)] = 75
        elif x == d_max:
                f[np.nditer(f)] = 75
print(f[np.nditer(f)])

<b style='color:darkred'> Porqué esto sí funciona...: </p>

In [ ]:
f[d<d_mean]=25
print(f)

<b style='color:darkred'> Pero esto no?:</p>


In [ ]:
f[d_min<d<d_mean]=25
print(f)

In [ ]:
f.any(d_mean<d<d_mean) = 25

#### **Compare directly inside f[]**: 
No need to limit min and max values as min and max are assigned later, so they will overwrite any previous value given

No se puede meter un array dentro de un índice, el índece debe ser entero (o boolean que es 1 o 0):

In [22]:
f[d]  

print(d)

IndexError: arrays used as indices must be of integer (or boolean) type

Pero sí puedes meter el resultado de una comparación. Y SE PUEDE COMPARAR UN ARRAY CON UN NÚMERO. COMPARA TODOS LOS ELEMENTOS!:

In [ ]:
f[d<d_mean]=25
f[d==d_min]=0
f[d==d_mean]=50
f[d==d_max]=100
print('d= \n', d,'\n\n', 'f= \n', f)

#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array(

        [[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])

In [ ]:
string = ["%.2f" % x for x in f]

In [ ]:
for x in f: 
    print("%.2f" % x)

In [ ]:
for x in f:
    f[x]=f[str(x)]

In [18]:
f[d > d_mean] = 'D'
f[d < d_mean] = 'B'
f[d == d_min] = 'A'
f[d == d_mean] = 'C'
f[d == d_max] = 'E'


ValueError: could not convert string to float: 'D'